#!/bin/bash
# Resymlink the web root to a specified directory
#
# Usage: wwwset [dir]
#
# If no dir is specified the current directory is used

WWW=/var/www

if [ "$#" == 0 ]; then
	DIR="$PWD"
elif [ -d "$1" ]; then
	DIR="$1"
else
	echo "$DIR is not a directory to link to $WWW"
	exit 1
fi

# Resolve $DIR to its absolute name (avoiding all symlinks)
cd "$DIR"
DIR=`pwd -P`

if [ ! -h "$WWW" ]; then
	echo "$WWW is not already a Symlink!"
	echo
	echo "This may just be because you have never run this script before OR that $WWW is a directory with actual contents"
	echo
	echo "Press enter THREE TIMES if you want to continue - YOU WILL LOSE ANYTHING IN $WWW"
	echo "Press Ctrl+C to abort"
	read; read; read
fi
sudo rm "$WWW"
sudo ln -s "$DIR" "$WWW"

echo "$WWW -> $DIR"
