#!/bin/bash
# Resymlink the web root to a specified directory
#
# Usage: wwwset [dir]
#
# If no dir is specified the current directory is used

# Your Apache directory
WWW=/var/www

# Detect NodeJS Gulp style projects and stop apache if found
NODE_GULP_DETECT=1

# Refuse to reset the WWW directory if its already correctly set - this can be annoying if a subprocess needs restarting but can prevent accidental nukes of Node processes
REFUSE_IF_SET=0

# Options to pass to a spawned terminal session
TERM_OPTS="--geometry -0-0 --profile=Log"

# -----

if [ "$#" == 0 ]; then
	DIR="$PWD"
elif [ -d "$1" ]; then
	DIR="$1"
else
	echo "$DIR is not a directory to link to $WWW"
	exit 1
fi

# Resolve $DIR to its absolute name (avoiding all symlinks)
cd "$DIR"
DIR=`pwd -P`

if [ ! -h "$WWW" ]; then
	echo "$WWW is not already a Symlink!"
	echo
	echo "This may just be because you have never run this script before OR that $WWW is a directory with actual contents"
	echo
	echo "Press enter THREE TIMES if you want to continue - YOU WILL LOSE ANYTHING IN $WWW"
	echo "Press Ctrl+C to abort"
	read; read; read
	sudo rm -r "$WWW"
fi

if [[ $REFUSE_IF_SET == 1 && `readlink "$WWW"` == "$DIR" ]]; then
	echo "WWW directory is already set to $DIR"
	exit 1
fi

echo "Setting WWW directory to $DIR..."

sudo rm "$WWW" 2>/dev/null
sudo ln -s "$DIR" "$WWW"

# Terminate Gulp if its running
ps -C gulp >/dev/null 2>&1
if [ "$?" == 0 ] ; then
	echo "Terminating existing gulp process..."
	killall gulp
fi

if [[ $NODE_GULP_DETECT == 1 && -e "gulpfile.js" ]]; then
	ps -C apache2 >/dev/null 2>&1
	if [ "$?" == 0 ]; then
		echo "Terminating Apache..."
		sudo service apache2 stop
	fi

	if [ -n "$COLORTERM" ]; then
		echo "Running Gulp in new terminal Window"
		eval "$COLORTERM $TERM_OPTS -x bash -ic 'gulp' &"
	else
		echo "Running Gulp inside screen session"
		screen -dmS gulp gulp
	fi

else
	# Assume this is a standard project that needs apache
	ps -C apache2 >/dev/null 2>&1
	if [ "$?" != 0 ]; then
		echo "Apache not running, starting..."
		sudo service apache2 start
	fi
fi

echo "$WWW -> $DIR"
